/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// P1 address and mask defines
#pragma	ioport	P1_Data_ADDR:	0x0
BYTE			P1_Data_ADDR;
#pragma	ioport	P1_DriveMode_0_ADDR:	0x100
BYTE			P1_DriveMode_0_ADDR;
#pragma	ioport	P1_DriveMode_1_ADDR:	0x101
BYTE			P1_DriveMode_1_ADDR;
#pragma	ioport	P1_DriveMode_2_ADDR:	0x3
BYTE			P1_DriveMode_2_ADDR;
#pragma	ioport	P1_GlobalSelect_ADDR:	0x2
BYTE			P1_GlobalSelect_ADDR;
#pragma	ioport	P1_IntCtrl_0_ADDR:	0x102
BYTE			P1_IntCtrl_0_ADDR;
#pragma	ioport	P1_IntCtrl_1_ADDR:	0x103
BYTE			P1_IntCtrl_1_ADDR;
#pragma	ioport	P1_IntEn_ADDR:	0x1
BYTE			P1_IntEn_ADDR;
#define P1_MASK 0x4
// P2 address and mask defines
#pragma	ioport	P2_Data_ADDR:	0x0
BYTE			P2_Data_ADDR;
#pragma	ioport	P2_DriveMode_0_ADDR:	0x100
BYTE			P2_DriveMode_0_ADDR;
#pragma	ioport	P2_DriveMode_1_ADDR:	0x101
BYTE			P2_DriveMode_1_ADDR;
#pragma	ioport	P2_DriveMode_2_ADDR:	0x3
BYTE			P2_DriveMode_2_ADDR;
#pragma	ioport	P2_GlobalSelect_ADDR:	0x2
BYTE			P2_GlobalSelect_ADDR;
#pragma	ioport	P2_IntCtrl_0_ADDR:	0x102
BYTE			P2_IntCtrl_0_ADDR;
#pragma	ioport	P2_IntCtrl_1_ADDR:	0x103
BYTE			P2_IntCtrl_1_ADDR;
#pragma	ioport	P2_IntEn_ADDR:	0x1
BYTE			P2_IntEn_ADDR;
#define P2_MASK 0x8
// P3 address and mask defines
#pragma	ioport	P3_Data_ADDR:	0x0
BYTE			P3_Data_ADDR;
#pragma	ioport	P3_DriveMode_0_ADDR:	0x100
BYTE			P3_DriveMode_0_ADDR;
#pragma	ioport	P3_DriveMode_1_ADDR:	0x101
BYTE			P3_DriveMode_1_ADDR;
#pragma	ioport	P3_DriveMode_2_ADDR:	0x3
BYTE			P3_DriveMode_2_ADDR;
#pragma	ioport	P3_GlobalSelect_ADDR:	0x2
BYTE			P3_GlobalSelect_ADDR;
#pragma	ioport	P3_IntCtrl_0_ADDR:	0x102
BYTE			P3_IntCtrl_0_ADDR;
#pragma	ioport	P3_IntCtrl_1_ADDR:	0x103
BYTE			P3_IntCtrl_1_ADDR;
#pragma	ioport	P3_IntEn_ADDR:	0x1
BYTE			P3_IntEn_ADDR;
#define P3_MASK 0x10
// P4 address and mask defines
#pragma	ioport	P4_Data_ADDR:	0x0
BYTE			P4_Data_ADDR;
#pragma	ioport	P4_DriveMode_0_ADDR:	0x100
BYTE			P4_DriveMode_0_ADDR;
#pragma	ioport	P4_DriveMode_1_ADDR:	0x101
BYTE			P4_DriveMode_1_ADDR;
#pragma	ioport	P4_DriveMode_2_ADDR:	0x3
BYTE			P4_DriveMode_2_ADDR;
#pragma	ioport	P4_GlobalSelect_ADDR:	0x2
BYTE			P4_GlobalSelect_ADDR;
#pragma	ioport	P4_IntCtrl_0_ADDR:	0x102
BYTE			P4_IntCtrl_0_ADDR;
#pragma	ioport	P4_IntCtrl_1_ADDR:	0x103
BYTE			P4_IntCtrl_1_ADDR;
#pragma	ioport	P4_IntEn_ADDR:	0x1
BYTE			P4_IntEn_ADDR;
#define P4_MASK 0x20
// STEP address and mask defines
#pragma	ioport	STEP_Data_ADDR:	0x4
BYTE			STEP_Data_ADDR;
#pragma	ioport	STEP_DriveMode_0_ADDR:	0x104
BYTE			STEP_DriveMode_0_ADDR;
#pragma	ioport	STEP_DriveMode_1_ADDR:	0x105
BYTE			STEP_DriveMode_1_ADDR;
#pragma	ioport	STEP_DriveMode_2_ADDR:	0x7
BYTE			STEP_DriveMode_2_ADDR;
#pragma	ioport	STEP_GlobalSelect_ADDR:	0x6
BYTE			STEP_GlobalSelect_ADDR;
#pragma	ioport	STEP_IntCtrl_0_ADDR:	0x106
BYTE			STEP_IntCtrl_0_ADDR;
#pragma	ioport	STEP_IntCtrl_1_ADDR:	0x107
BYTE			STEP_IntCtrl_1_ADDR;
#pragma	ioport	STEP_IntEn_ADDR:	0x5
BYTE			STEP_IntEn_ADDR;
#define STEP_MASK 0x1
// DIR address and mask defines
#pragma	ioport	DIR_Data_ADDR:	0x4
BYTE			DIR_Data_ADDR;
#pragma	ioport	DIR_DriveMode_0_ADDR:	0x104
BYTE			DIR_DriveMode_0_ADDR;
#pragma	ioport	DIR_DriveMode_1_ADDR:	0x105
BYTE			DIR_DriveMode_1_ADDR;
#pragma	ioport	DIR_DriveMode_2_ADDR:	0x7
BYTE			DIR_DriveMode_2_ADDR;
#pragma	ioport	DIR_GlobalSelect_ADDR:	0x6
BYTE			DIR_GlobalSelect_ADDR;
#pragma	ioport	DIR_IntCtrl_0_ADDR:	0x106
BYTE			DIR_IntCtrl_0_ADDR;
#pragma	ioport	DIR_IntCtrl_1_ADDR:	0x107
BYTE			DIR_IntCtrl_1_ADDR;
#pragma	ioport	DIR_IntEn_ADDR:	0x5
BYTE			DIR_IntEn_ADDR;
#define DIR_MASK 0x2
